### ISSUE TITLE
Issue with expokit time-propagator

### ISSUE THREAD

**Issue by yachmena** [CFEL-CMI/richmol#12]

**Comment by saribalc** [comment]
@yachmena, applying a threshold of `1e-12` to norm of `H` does not solve the problem for me.

In our `test_tdse` test `zhexpv` will not be used during the first call of `TDSE.update()` (norm = 6.042e-34). All fine until here. But during the second call of `TDSE.update()` `zhexpv` will be called (norm = 0.161) leading to the same 'happy breakdown...' error seen above.

I guess I have to play around with different versions of the fortran compiler or so. Maybe this will solve the problem for me.

**Comment by yachmena** [comment]
Hi @saribalc, for me everything works just fine, I also tested on Maxwell and the `test_tdse.py` ran OK.

**Comment by saribalc** [comment]
Hi @yachmena , thanks for letting me know. Then I guess the problem lies in my conda environment and we can finally close this issue.
