### ISSUE TITLE
Add examples of spectrum simulations

### ISSUE THREAD

**Issue by yachmena** [CFEL-CMI/richmol#15]
@saribalc and @yangguang888, please make few examples for calculations using spectrum.py as well as field-dressed spectra

Please update the following files (the corresponding richmol file will be automatically downloaded)

- [h2o_dipole_spectrum.py](https://github.com/CFEL-CMI/richmol/blob/develop/examples/h2o_dipole_spectrum.py)
- [h2o_dipole_spectrum_in_field.py](https://github.com/CFEL-CMI/richmol/blob/develop/examples/h2o_dipole_spectrum_in_field.py)
- [h2o_quadrupole_spectrum.py](https://github.com/CFEL-CMI/richmol/blob/develop/examples/h2o_quadrupole_spectrum.py)

**Comment by saribalc** [comment]
The `h2o_dipole_spectrum_in_field` leads to the following spectrum for `j_max = 5`, `e_max = 1e4` and `field = [0, 0, 1e3]`:

![spectrum](https://user-images.githubusercontent.com/68108025/122652919-c568ef00-d141-11eb-82e2-68a9d9767160.png)

Note that, compared to the field-free dipole spectrum (see above), absorption intensities are not as great. This most likely is caused by the external field breaking degeneracy w.r.t. M quantum number.

**Comment by saribalc** [comment]
I suspect, that the intensities scattered above the usual hill structure in field-free spectra are introduced by how the degeneracy w.r.t M quantum number is currently handled in the `spectrum` module:

Currently degenerate linestrengths are computed by summing up (m_bra, m_ket) - sub-matrices of the linestrength matrix. The reason for this kind of implementation lies in the compatibility to cases with more than one irreducible representation.

Alternatively, and if only one irreducible representation exists, degenerate linestrengths can also be computed by simply loading cartesian tensors for only one M quantum number pair (e.g. (0.0, 0.0)) and directly multiplying resulting k-tensors with the degeneracy factor (2*j_bra + 1) * (2*j_ket + 1).

This alternative I will try out after finishing some other stuff. Therefore this issue will be shifted to 'To Do' for now.

**Comment by saribalc** [comment]
Hi @yachmena and @yangguang888 , I managed to hunt down the annoying bug, which caused scattered intensities in `spectrum` module (pls see issue closing commit). 🥇 Took me only one day 🥇

dipole after scattered intensities fix (zenodo data):
![dip_jmax30 0](https://user-images.githubusercontent.com/68108025/122986968-5e954100-d3a0-11eb-88e4-89be8063714f.png)

quadrupole after scattered intensities fix (zenodo data):
![quad_jmax30 0](https://user-images.githubusercontent.com/68108025/122987164-943a2a00-d3a0-11eb-8abb-4c13df913a57.png)
