### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by mlawson00** [CFEL-CMI/richmol#22]
Hi there, 

I'm having trouble building  - I have multiple complication errors. I was wondering if there was a requirement on the Fortran compiler needed? I've tried GCC 9-11 with no success. 

Any advice would be appreciated.

Many thanks, 

Mike

**Comment by yachmena** [comment]
Hello, Mike.
I apologise for the delay in responding; I haven't received any issue notifications from github.
Could you please send me (post here) the compilation output so that I can best assist you?

**Comment by mlawson00** [comment]
Hi there,

Thanks for getting back to me. I fixed it by downgrading Fortran to some older version. It wasn't so straightforward, since I had to use an old version of Ubuntu even to install the old Fortran in the first place. Anyway, after this your program worked fantastically well - thank you, it saved me a lot of headaches dealing with the Stark effect!!

Best Wishes,

Mike
