### ISSUE TITLE
Unable to tdse.initial_state

### ISSUE THREAD

**Issue by nidin1996** [CFEL-CMI/richmol#24]
Unable to generate initial states for Jmax greater than 40. I can't take H_diag niehter sparse form of the matrix. The error file is attached below.

[3655128.txt](https://github.com/CFEL-CMI/richmol/files/12857595/3655128.txt)

**Comment by nidin1996** [comment]
There is an option of using H_is_diag  in init_state, it is not used. 
[3707876.txt](https://github.com/CFEL-CMI/richmol/files/12913233/3707876.txt)


If h0 is convereted to a matirx using h0.tomat(form = 'block', cart = 0), attribute error is raised as init_state checks for type of H.
[3748082.txt](https://github.com/CFEL-CMI/richmol/files/12913228/3748082.txt)

**Comment by yachmena** [comment]
@nidin1996, I have updated the `tdse.init_state()` to work with a sparse-matrix representation of the initial state vectors, see https://github.com/CFEL-CMI/richmol/commit/628d8917c7c8c1c45dd3802a03d219378ee4f454
The function doesn't allocate anymore large dense arrays for the diagonal Hamiltonian. For high temperatures, i.e., if a large number of initial states gets populated, it makes sense to keep the output initial state vectors in a sparse-matrix representation. You can do it by passing `sparse=True` to the `tdse.init_state()` function.
